### ISSUE TITLE
What to do with the default labels?

### ISSUE THREAD

**Issue by choxx** [Samagra-Development/quml2xform#2]
Referring to the template shared earlier: https://docs.google.com/spreadsheets/d/1GIcHghGYUR1FZ31BD-LCXBNMzr1xdCmQ/edit#gid=1148196142

![image](https://user-images.githubusercontent.com/11666456/180777351-0602ff59-2931-401b-80a9-19dfda7ced04.png)

The intro for the form is currently hard coded along with a few other text/labels. Is that fine? Ref: https://github.com/choxx/quml2xform/blob/78f277a8076fea7354f9b8a7d9e7989a51373c8e/src/quml-to-odk/quml-to-odk.service.ts#L194

**Comment by ChakshuGautam** [comment]
@choxx is this closed now?

**Comment by choxx** [comment]
> @choxx is this closed now?

Yes, confirmed with @tarang; it's fine as it is. Closing the ticket.
